AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an RDS DB instance that is restored from a DB snapshot.

# The following metadata is used to group the parameters
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: Export VPC Stack Name
        Parameters:
          - ExportVpcStackName
      - 
        Label: 
          default: Database Parameters
        Parameters:
          - DatabaseInstanceIdentifier
          - DatabaseSnapshotIdentifier
          - DatabaseInstanceClass
          - MultiAZDatabase

# Parameters are used to to build flexible CloudFormation templates
Parameters:
  ExportVpcStackName:
    Description: The name of the VPC stack that exports values.
    Type: String

  DatabaseInstanceIdentifier:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Default: mysqldb
    Description: Instance identifier name.
    MaxLength: 60
    MinLength: 1
    Type: String

  DatabaseSnapshotIdentifier:
    Description: The ARN of the DB snapshot that's used to restore the DB instance.
    Type: String

  DatabaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    ConstraintDescription: Must select a valid database instance type.
    Default: db.t2.micro
    Description: The database instance type.
    Type: String

  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true or false.
    Default: false
    Description: Create a Multi-AZ MySQL Amazon RDS database instance.
    Type: String

Resources:
  # Create database subnet group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database.
      SubnetIds: 
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateDataSubnet1
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateDataSubnet2
      Tags:
        - Key: Name
          Value: Database Subnets

  # Create database from RDS snapshot
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
      DBSnapshotIdentifier: !Ref DatabaseSnapshotIdentifier
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: MySQL
      MultiAZ: !Ref MultiAZDatabase
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-DatabaseSecurityGroup